[project]
name = "owt"
version = "0.0.1"

[tool.setuptools.packages.find]
where = ["owt"]

[tool.mypy]
packages = "owt"
enable_incomplete_feature = "NewGenericSyntax"
check_untyped_defs = true

[tool.pylsp-mypy]
enabled = true
live_mode = true
strict = true
